# -*- coding: utf-8 -*-
"""
Odoo Proprietary License v1.0.

see License:
https://www.odoo.com/documentation/user/16.0/legal/licenses/licenses.html#odoo-apps
# Copyright ©2023 Bernard K. Too<bernard.too@optima.co.ke>
"""
from num2words import num2words

from odoo import _, api, fields, models


class SO(models.Model):
    _inherit = ["sale.order"]

    @api.onchange("partner_id")
    def onchange_partner_style(self):
        self.style = (
            self.partner_id.style
            or self.env.user.company_id.df_style
            or self.env.ref("customized_invoice.df_style_for_all_reports")
        )

    style = fields.Many2one(
        "report.template.settings",
        "Quote/Order Style",
        help="Select Style to use when printing the Sales Order or Quote",
        default=lambda self: self.partner_id.style or self.env.user.company_id.df_style,
    )
    project_title = fields.Char(
        "Title",
        help="The title of your customer project or work you are doing for your customer",
    )
    amount_words = fields.Char(
        "Amount in Words:",
        help="The total amount in words is automatically generated by the system..few languages are supported currently",
        compute="_compute_num2words",
    )

    def _compute_num2words(self):
        for rec in self:
            style = (
                rec.style
                or rec.partner_id.style
                or rec.env.user.company_id.df_style
                or rec.env.ref("customized_invoice.df_style_for_all_reports")
            )
            if style and style.aiw_report:
                try:
                    rec.amount_words = num2words(
                        rec.amount_total, lang=rec.partner_id.lang or "en"
                    ).upper()
                except NotImplementedError:
                    rec.amount_words = num2words(rec.amount_total, lang="en").upper()
            else:
                rec.amount_words = _("Disabled")
